version: "3.9"
services:
  db:
    image: postgres:14.3-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network
    volumes:
      - nodes_and_edges:/var/lib/postgresql/data
      - ./backend/db.sql:/docker-entrypoint-initdb.d/db.sql
networks:
  app-network:
volumes:
  nodes_and_edges: