"""Change table attributes

Revision ID: 2221a471ed49
Revises: 8bc88d70eb6c
Create Date: 2022-10-23 18:38:45.281037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2221a471ed49'
down_revision = '8bc88d70eb6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge', sa.Column('label', sa.String(length=100), nullable=True))
    op.drop_column('edge', 'name')
    op.add_column('node', sa.Column('term', sa.String(length=100), nullable=True))
    op.add_column('node', sa.Column('definition', sa.Text(), nullable=True))
    op.drop_column('node', 'name')
    op.drop_column('node', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('node', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('node', 'definition')
    op.drop_column('node', 'term')
    op.add_column('edge', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('edge', 'label')
    # ### end Alembic commands ###
