"""Added column 'name' (Edge)

Revision ID: 8bc88d70eb6c
Revises: 2f661334a302
Create Date: 2022-10-22 21:44:23.334325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc88d70eb6c'
down_revision = '2f661334a302'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edge', 'name')
    # ### end Alembic commands ###
