"""Added unique attribute to Node.term

Revision ID: 9bd7ff2270b3
Revises: 3e71ead4a59a
Create Date: 2022-10-23 20:48:53.475209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd7ff2270b3'
down_revision = '3e71ead4a59a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'node', ['term'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'node', type_='unique')
    # ### end Alembic commands ###
